#work_dir: ./work_dir_19_points_FAN_6_layers_train_on_300W_LP_test_on_BIWI/GCN_head_pose
work_dir: work_dir_19_points_FAN_6_layers_train_on_300W_LP_test_on_BIWI/GCN_head_pose/epoch107_model_mae_4.076589107513428.pt

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: False
  random_move: False
  window_size: 1
  data_path: /home/xinmiao/intern/MoShentong/CVPRW2021/data/FAN/300W_LP_19_points/point19_train_data.npy
  label_path: /home/xinmiao/intern/MoShentong/CVPRW2021/data/FAN/300W_LP_19_points/point19_train_label.npy
  #data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/300W_LP_19_points/new_train_data.npy
  #label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/300W_LP_19_points/new_train_label.npy
test_feeder_args:
  #data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_total_19_points/BIWI_data_angle99.npy
  #label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_total_19_points/BIWI_label_angle99.npy
  #data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_total_19_points/BIWI_data_angle99_no_track.npy
  #label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_total_19_points/BIWI_label_angle99_no_track.npy
  #data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/change_biwi/BIWI_train_19_points/BIWI_train_data_angle99.npy
  #label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/change_biwi/BIWI_train_19_points/BIWI_train_label_angle99.npy
  data_path: /home/xinmiao/intern/MoShentong/CVPRW2021/data/mtcnn/BIWI_data_mtcnn_angle99_no_track.npy
  label_path: /home/xinmiao/intern/MoShentong/CVPRW2021/data/mtcnn/BIWI_label_mtcnn_angle99_no_track.npy

# model
model: net.st_gcn_attention.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_19_points'
    strategy: 'spatial'

# training
device: [0,1]           # [0, 1, 2, 3]
batch_size: 512     # 256 
test_batch_size: 512   # 256

#optim
base_lr: 0.1
step: [50, 150, 170]
num_epoch: 200



