weights: /home/intern2/yuanzelin/GCN_head_pose_test/work_dir_19_points_OpenPose_BIWI_5_layers/GCN_head_pose/epoch51_model_mae_5.579723834991455.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
    data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/OpenPose/BIWI_test_19_points/BIWI_test_data_angle99.npy
    label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/OpenPose/BIWI_test_19_points/BIWI_test_label_angle99.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_19_points'
    strategy: 'spatial'

# test 
phase: test
device: [0,1]
test_batch_size: 1024
