work_dir: ./work_dir_19_points_FAN_BIWI_new/recognition/Head_Pose/GCN_head_pose

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: False
  random_move: False
  window_size: 1
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_train_19_points/0.7/BIWI_train_data_0.7_angle99.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_train_19_points/0.7/BIWI_train_label_0.7_angle99.npy
test_feeder_args:
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_test_19_points/0.3/BIWI_test_data_0.3_angle99.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_test_19_points/0.3/BIWI_test_label_0.3_angle99.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_19_points'
    strategy: 'spatial'

# training
device: [0,1]           # [0, 1, 2, 3]
batch_size: 256      # 256 
test_batch_size: 256   # 256

#optim
base_lr: 0.1
step: [40, 70, 80, 90]
num_epoch: 100



