# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_18_points'
    strategy: 'spatial'

# test 
phase: test
device: [0,1]
test_batch_size: 256
