weights: /home/intern2/yuanzelin/GCN_head_pose_test/work_dir_19_points_FAN_5_layers_no_attention/recognition/GCN_head_pose/epoch5_model_mae_7.5845112800598145.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_19_points/max_angle_99/AFLW2000_FAN_data_angle99.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_19_points/max_angle_99/AFLW2000_FAN_label_angle99.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: False
  graph_args:
    layout: 'openpose_face_19_points'
    strategy: 'spatial'

# test 
phase: test
device: [0,1]
test_batch_size: 256
