weights: /home/intern2/yuanzelin/GCN_head_pose_test/work_dir_FAN_25_points_5_layer/GCN_head_pose/epoch11_model_mae_7.583425045013428.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_25_points/max_angle_99/AFLW2000_data_angle99.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_25_points/max_angle_99/AFLW2000_label_angle99.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_25_points'
    strategy: 'spatial'

# test 
phase: test
device: [0,1]
test_batch_size: 256
