#weights: /home/intern2/yuanzelin/GCN_head_pose_test/work_dir_19_points_FAN_5_layers_no_attention/recognition/GCN_head_pose/epoch34_model_mae_7.630712032318115.pt
#weights: /home/intern2/yuanzelin/GCN_head_pose_test/work_dir_19_points_FAN_test/6_layers/best/epoch34_model_mae_6.93388032913208.pt
#weights: work_dir_19_points_gt_6_layers_train_on_300W_LP_test_on_BIWI/GCN_head_pose/epoch48_model_mae_3.995140790939331.pt
#weights: /home/intern2/yuanzelin/GCN_head_pose_test/work_dir_19_points_FAN_6_layers_train_on_300W_LP_test_on_BIWI/GCN_head_pose/epoch73_model_mae_4.164283752441406.pt
weights: work_dir_19_points_FAN_6_layers_train_on_300W_LP_test_on_BIWI/GCN_head_pose/epoch107_model_mae_4.076589107513428.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
#  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/AFLW2000/test_data_2d.npy
#  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/AFLW2000/test_label.npy
 # data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/AFLW2000_19_points/new/AFLW2000_data_angle99.npy
 # label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/AFLW2000_19_points/new/AFLW2000_label_angle99.npy
#  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_19_points/max_angle_99/AFLW2000_FAN_data_angle99.npy
#  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_19_points/max_angle_99/AFLW2000_FAN_label_angle99.npy
  data_path: data/mtcnn/BIWI_data_mtcnn_angle99_no_track.npy
  label_path: data/mtcnn/BIWI_label_mtcnn_angle99_no_track.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_19_points'
    strategy: 'spatial'

# test 
phase: test
device: [0,1]
test_batch_size: 256
