#weights: /home/intern2/yuanzelin/GCN_head_pose_test/work_dir_19_points_FAN_5_layers_no_attention/recognition/GCN_head_pose/epoch34_model_mae_7.630712032318115.pt
weights: /home/intern2/yuanzelin/GCN_head_pose_test/paper/FAN/FAN_300W_LP/19_points/594KB_5_layers_gcn/recognition/Head_Pose/GCN_head_pose/best_model/epoch4_model_mae_6.860689640045166.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_total_19_points/BIWI_data_angle99.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/BIWI_total_19_points/BIWI_label_angle99.npy
  
# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_19_points'
    strategy: 'spatial'

# test 
phase: test
device: [0,1]
test_batch_size: 256
