work_dir: ./work_dir_19_points_Dlib/5_layers
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: False
  random_move: False
  window_size: 1
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/Dlib/data/point19_train_data.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/Dlib/data/point19_train_label.npy
test_feeder_args:
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/Dlib/label/AFLW2000_data_angle180.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/Dlib/label/AFLW2000_label_angle180.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose_face_19_points'
    strategy: 'spatial'

# training
device: [0,1]           # [0, 1, 2, 3]
batch_size: 256      # 256 
test_batch_size: 256   # 256

#optim
#base_lr: 0.2
#step: [20, 30, 40, 45]
#num_epoch: 100
base_lr: 0.1
step: [50, 100, 150, 170]
num_epoch: 200



