work_dir: ./work_dir_FAN_25_points_5_layer_no_attention/GCN_head_pose

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: False
  random_move: False
  window_size: 1
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/300W_LP_25_points/new_train_data_25_points.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/300W_LP_25_points/new_train_label_25_points.npy

test_feeder_args:
  data_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_25_points/no_limit/AFLW2000_data_angle180.npy
  label_path: /home/intern2/yuanzelin/GCN_head_pose_test/data/FAN/AFLW2000_25_points/no_limit/AFLW2000_label_angle180.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 3
  edge_importance_weighting: False
  graph_args:
    layout: 'openpose_face_25_points'
    strategy: 'spatial'

# training
device: [0,1]           # [0, 1, 2, 3]
batch_size: 256      # 256 
test_batch_size: 256   # 256

#optim
base_lr: 0.1
step: [40, 70, 90, 95]
num_epoch: 100



